### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by KeMura-ops** [KeMura-ops/furima-32865#9]
**フリマアプリ本番環境URL:**  
https://furima-32865.herokuapp.com/

**Basic認証のIDとパスワード** 
ID: admin 
PASS: 2222

**出品者用のメールアドレスとパスワード** 
Mail: sample@example.com 
PASS:  Hui86s

**購入者用のメールアドレスとパスワード** 
Mail: tests@example.com 
PASS: Lp4567

**購入用カードの番号・期限・セキュリティコード**
カード番号: 4242424242424242
CVC: 123
期限: 3 / 23

**Comment by hideaki0806** [comment]
**KeMura-ops** さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**
◉商品編集ページにて、必要な情報を適切に入力すると、商品情報（商品画像・商品名・商品の状態など）を
変更できるようにしましょう

詳細：現状、値段が変更できません。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by KeMura-ops** [comment]
挙動確認ありがとうございます。
指摘箇所である値段変更が可能になるように修正いたしましたにでご確認お願いいたします。

**Comment by MakiTaka** [comment]
@KeMura-ops さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
